### PR TITLE
Fixes #YUPTOO-67 - Bump pytest version

### PR DESCRIPTION
**Pull request by saltgen**
Minimal locking of pytest with suggested version on dependabot alert.
Currently, a minimum version locking is not present in Pipfile for the package.

Please check JIRA card for details

### CODE REVIEW

**Review by kgaikwad — CHANGES_REQUESTED** [review]
Looks good. Due to recent merge it is facing conflicts for Pipfile.lock, could you please do rebase?

**Comment by saltgen** [comment]
> Looks good. Due to recent merge it is facing conflicts for Pipfile.lock, could you please do rebase?

@kgaikwad Done, changes pushed

**Review by kgaikwad — APPROVED** [review]
Legit :+1:

**Pull request merged**
