### PR TITLE
Refs #YUPTOO-27 - Remove account number from outbound data.

### PR DESCRIPTION
**Pull request by patilsuraj767**

### CODE REVIEW

**Review by kgaikwad — APPROVED** [review]
Legit

**Comment by lphiri** [comment]
@patilsuraj767 @kgaikwad  the account number is still  useful data to have.  Even orgs that start without one will eventually get one generated, so I suggest keeping it as optional. Any particular reason you are removing it?

**Comment by kgaikwad** [comment]
> @patilsuraj767 @kgaikwad the account number is still useful data to have. Even orgs that start without one will eventually get one generated, so I suggest keeping it as optional. Any particular reason you are removing it?

This was added because step was mentioned under level 3 migration, right @patilsuraj767?
I noticed your [ping](https://coreos.slack.com/archives/C03B7U5AE67/p1660652929172819) on slack channel regarding this.
@patilsuraj767  -  Can we revert this change and make it optional?

**Comment by lphiri** [comment]
@kgaikwad  I see.   Just hang on  a sec and let me discuss with the team.  I was not aware we had added that requirement in the level 3 migration.

**Comment by patilsuraj767** [comment]
As per Jira it says remove EAN (or make it optional) - https://issues.redhat.com/browse/YUPANA-110
I decided to remove it because our services does rely on account number nor the org_id. Also tested this changes with latest HBI image, HBI was able to store host in DB without account number.

**Pull request merged**
