### PR TITLE
EBS to org_id migration changes

### PR DESCRIPTION
**Pull request by patilsuraj767**

### CODE REVIEW

**Review by r14chandra — APPROVED** [review]
This looks good! 
Noticed one thing, under `platform_metadata` field we just send `request_id` and `b64_identity` not other fields which we get from Ingress like `org_id`, `account` and others. Should we also include them?

**Comment by patilsuraj767** [comment]
@r14chandra Yupana does not include any other field so I have not added it in yuptoo too. Does puptoo includes org_id and account under `platform_metadata`?

**Comment by patilsuraj767** [comment]
@r14chandra Yupana does not include any other fields, To make Yuptoo equivalent to Yupana I think for now we can skip `org_id`, `account` ad other fields in `platform_metadata`.

**Comment by r14chandra** [comment]
Sure! we can merge this PR then.

**Pull request merged**
