### PR TITLE
Revert "Revert "Refs #RHINENG-2640 - set reporter to "discovery" or "…

### PR DESCRIPTION
**Pull request by JoySnow**
…satellite" (#71)" (#75)"

This reverts commit ab64ae18fdfeefebe675c2eecbc8f67206b11a05.

Redo this change to main branch.

### CODE REVIEW

**Comment by Aurobinda55** [comment]
fixed pr checks -  https://gitlab.cee.redhat.com/insights-qe/iqe-foreman-rh-cloud-plugin/-/merge_requests/174/diffs

**Comment by JoySnow** [comment]
Many thanks @Aurobinda55 for the fix.

**Comment by xiangce** [comment]
@JoySnow - this change looks good to me

**Pull request merged**
