### PR TITLE
[YUPTOO-23] Add Kafka auth config

### PR DESCRIPTION
**Pull request by patilsuraj767**

### CODE REVIEW

**Review by r14chandra — APPROVED** [review]
looks good!

**Comment by r14chandra** [comment]
Thanks @patilsuraj767! Merging it.

**Comment by kgaikwad** [comment]
Hello @patilsuraj767 - 
Added JIRA card - https://issues.redhat.com/browse/YUPTOO-23
Could you add ticket number into commit message and update JIRA card with more details.

**Comment by r14chandra** [comment]
Thanks @patilsuraj767! Merging this PR.

**Pull request merged**
